steps:
  - module_header:
       indent: 4
       sort: true
       separate_lists: true
       break_where: single
       open_bracket: next_line

  - records:
       equals: "indent 2"
       first_field: "indent 2"
       field_comment: 2
       deriving: 2
       via: "indent 2"
       sort_deriving: true
       break_enums: true
       break_single_constructors: true
       curried_context: false

  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always

  - imports:
      align: group
      list_align: after_alias
      pad_module_names: true
      long_list_align: inline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
      post_qualify: true
  - language_pragmas:
      style: vertical
      align: true
      remove_redundant: true
      language_prefix: LANGUAGE

  - trailing_whitespace: {}

columns: 100
newline: lf

language_extensions:
  - TemplateHaskell
  - QuasiQuotes
  - OverloadedLabels
  - TypeApplications

cabal: true
